name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Install CocoaPods
        run: |
          brew install cocoapods
          pod install
        working-directory: ./SwiftUINavigation

      - name: Build
        run: |
          set -eo pipefail
          xcodebuild \
          -workspace SwiftUINavigation.xcworkspace \
          -scheme SwiftUINavigation \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.2' \
          ONLY_ACTIVE_ARCH=YES | xcpretty
        working-directory: ./SwiftUINavigation
